import React, { useState, useEffect } from 'react';
import { getAccessToken, googleSignIn } from '../lib/firebase';
import { FolderOpen, Search, FileText, Image as ImageIcon, Loader2, AlertCircle, ExternalLink } from 'lucide-react';
import { motion } from 'motion/react';

interface DriveFile {
  id: string;
  name: string;
  mimeType: string;
  thumbnailLink?: string;
  iconLink?: string;
  webViewLink?: string;
  createdTime?: string;
}

export function Library() {
  const [files, setFiles] = useState<DriveFile[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState('');

  useEffect(() => {
    fetchFiles();
  }, []);

  const fetchFiles = async () => {
    setIsLoading(true);
    setError(null);
    try {
      const token = await getAccessToken();
      if (!token) {
        throw new Error("Missing Google authentication. Please reconnect.");
      }

      const res = await fetch('/api/drive/list', {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });
      
      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || "Failed to fetch library files");
      }
      
      // Filter for files created by this app (Meeting Notes, Generated Designs, etc.)
      const relevantFiles = (data.files || []).filter((f: DriveFile) => {
        const n = f.name.toLowerCase();
        return n.includes('meeting') || n.includes('design') || n.includes('generated');
      });
      
      setFiles(relevantFiles);
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Could not load library");
    } finally {
      setIsLoading(false);
    }
  };

  const filteredFiles = files.filter(f => f.name.toLowerCase().includes(searchQuery.toLowerCase()));

  return (
    <div className="flex flex-col h-full bg-[#FAFAFA] relative overflow-hidden">
      <header className="px-8 py-6 border-b border-stone-200/50 bg-white/50 backdrop-blur-md flex-shrink-0 relative z-10 hidden md:block">
        <div className="max-w-6xl mx-auto flex flex-col gap-4">
          <div className="flex items-center justify-between">
            <h1 className="text-2xl font-semibold text-stone-900 tracking-tight">Library</h1>
          </div>
          <p className="text-stone-500 text-sm max-w-2xl">
            View all content generated by the AI, including meeting notes and visual designs, saved directly to your Google Drive.
          </p>
        </div>
      </header>

      <div className="flex-1 overflow-y-auto px-4 md:px-8 py-6 pb-20 md:pb-8 relative z-0">
        <div className="max-w-6xl mx-auto">
          <div className="mb-6 flex">
             <div className="relative flex-1 max-w-sm">
               <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-stone-400" />
               <input 
                 type="text" 
                 placeholder="Search files..."
                 value={searchQuery}
                 onChange={(e) => setSearchQuery(e.target.value)}
                 className="w-full pl-9 pr-4 py-2 bg-white border border-stone-200 rounded-lg text-sm text-stone-800 placeholder:text-stone-400 focus:outline-none focus:ring-2 focus:ring-stone-200 focus:border-stone-300 transition-all"
               />
             </div>
          </div>

          {isLoading ? (
            <div className="flex items-center justify-center py-20 text-stone-500">
              <Loader2 className="w-8 h-8 animate-spin text-stone-400 mb-4" />
            </div>
          ) : error ? (
            <div className="bg-red-50 text-red-600 rounded-xl p-4 flex flex-col items-center justify-center py-10">
              <AlertCircle className="w-8 h-8 mb-2 opacity-80" />
              <p className="font-semibold text-sm">Failed to load library</p>
              <p className="text-xs opacity-80 mt-1 max-w-sm text-center">{error}</p>
              <div className="flex items-center gap-2 mt-4">
                <button onClick={fetchFiles} className="px-4 py-2 bg-white rounded-lg border border-red-200 text-sm font-medium text-red-600 hover:bg-red-50">Try Again</button>
                {error.includes("Missing Google authentication") && (
                  <button 
                    onClick={async () => {
                      try {
                        await googleSignIn();
                        fetchFiles();
                      } catch (err: any) {
                        console.error(err);
                        if (err?.code === 'auth/popup-blocked' || err?.code === 'auth/cancelled-popup-request') {
                          alert('Popup blocked. Please open this app in a new tab using the "Open in new tab" button at the top right of the preview window to sign in.');
                        } else {
                          alert(`Sign in error: ${err.message || 'Unknown error'}`);
                        }
                      }
                    }} 
                    className="px-4 py-2 bg-red-600 text-white rounded-lg font-medium text-sm hover:bg-red-700 transition"
                  >
                    Reconnect with Google
                  </button>
                )}
              </div>
            </div>
          ) : filteredFiles.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-20 text-stone-400 bg-white border border-stone-100 rounded-2xl shadow-sm">
              <FolderOpen className="w-12 h-12 mb-4 opacity-50" />
              <p className="text-sm font-medium text-stone-600">No files found</p>
              <p className="text-xs text-stone-400 mt-1">Generated designs and notes will appear here.</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
              {filteredFiles.map((file, i) => (
                <motion.a
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.05 }}
                  key={file.id}
                  href={file.webViewLink}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="group bg-white border border-stone-200 rounded-xl overflow-hidden hover:shadow-md transition-all hover:border-stone-300 flex flex-col h-64"
                >
                  <div className="flex-1 bg-stone-50 relative flex items-center justify-center p-4 border-b border-stone-100/80 overflow-hidden">
                    {file.thumbnailLink ? (
                      <img src={file.thumbnailLink} alt={file.name} className="w-full h-full object-cover rounded-md shadow-sm" />
                    ) : file.mimeType.includes('image') ? (
                      <ImageIcon className="w-10 h-10 text-stone-300" />
                    ) : (
                      <FileText className="w-10 h-10 text-stone-300" />
                    )}
                    
                    <div className="absolute inset-0 bg-stone-900/0 group-hover:bg-stone-900/5 transition-colors flex items-center justify-center">
                       <div className="opacity-0 group-hover:opacity-100 transition-opacity translate-y-2 group-hover:translate-y-0 bg-white/90 backdrop-blur text-stone-700 px-3 py-1.5 rounded-full text-xs font-semibold shadow-sm flex items-center gap-1.5">
                         View in Drive <ExternalLink className="w-3 h-3" />
                       </div>
                    </div>
                  </div>
                  
                  <div className="p-4 bg-white flex flex-col justify-between shrink-0">
                    <div className="flex items-start gap-2 max-w-full">
                      {file.iconLink && <img src={file.iconLink} alt="" className="w-4 h-4 mt-0.5 shrink-0" />}
                      <h3 className="font-semibold text-sm text-stone-800 line-clamp-1 break-all" title={file.name}>{file.name}</h3>
                    </div>
                    {file.createdTime && (
                       <p className="text-[11px] text-stone-400 mt-2 font-medium">
                         {new Date(file.createdTime).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}
                       </p>
                    )}
                  </div>
                </motion.a>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
